### ISSUE TITLE
Section suggestion

### ISSUE THREAD

**Issue by MEEPofFaith** [SimonWoodburyForget/mindustry-modding#10]
Have a small section (maybe under _7. Other_) for how to add text formatting to item/block descriptions (like the Router's red text) or for the mod.json with a colored title or description.

**Comment by MEEPofFaith** [comment]
Also note if there are set colors (and maybe a list or link to one) or if you can just put a hex color line in

**Comment by MEEPofFaith** [comment]
You can put in a hex line or a valid color word.
[word]text[]
[#hex code]text[]

**Comment by SimonWoodburyForget** [comment]
Color strings seem to be initialized from this class: https://github.com/Anuken/Arc/blob/411d2784f538dfc10db2962a62833938029dafdd/arc-core/src/io/anuke/arc/graphics/Colors.java meaning a full list would be:

```
[clear]clear
[black]black
[white]white
[lightgray]lightgray
[gray]gray
[darkgray]darkgray
[blue]blue
[navy]navy
[royal]royal
[slate]slate
[sky]sky
[cyan]cyan
[teal]teal
[green]green
[acid]acid
[lime]lime
[forest]forest
[olive]olive
[yellow]yellow
[gold]gold
[goldenrod]goldenrod
[orange]orange
[brown]brown
[tan]tan
[brick]brick
[red]red
[scarlet]scarlet
[coral]coral
[salmon]salmon
[pink]pink
[magenta]magenta
[purple]purple
[violet]violet
[maroon]maroon
```

`[color]` is only required to change the color of the next words and `[]` only goes back to white. Invalid colors just get ignored like `[notcolor]xxx` comes how as `[notcolor]xxx` instead of `xxx`.

Transparency is also valid:

```
[#ff0000]red
[#ff000066]halfred
[#ff000033]halfhalfred
```

The markup as documented in libgdx is here: https://github.com/libgdx/libgdx/wiki/Color-Markup-Language
